steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim \
    --token "bjKUlzoLS6FuJvEKD2V3KADDygVRNhyJnfYrAqu9MoSmtmyF2C" \
    --project "tNnA05XxVuNZHQnX8Ygd" \
    --grid "Testim-Grid" \
    --suite "Test Demo" \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  displayName: 'publish testim test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml'
